# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  iOS: /tags/iOS
   

# SubNav
subnav:
  github: "https://github.com/jackhub"
  weibo: "http://weibo.com/iwaich"
  rss: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
google_analytics: ''
favicon: /img/jj.png

#你的头像
avatar: /img/longmao.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
#friends:


#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
#aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…